create DATABASE BMS_DB1;

USE BMS_DB1;

-- CUSTOMER_PERSONAL_INFO
CREATE TABLE CUSTOMER_PERSONAL_INFO
(
CUSTOMER_ID VARCHAR(5),
CUSTOMER_NAME VARCHAR(50),
DOB DATE,
GAURDIAN_NAME VARCHAR(50),
CONTACT_NO BIGINT(10),
MAIL_ID VARCHAR(30),
GENDER CHAR(1),
MARTIAL_STATUS VARCHAR(10),
IDENTICATION_DOC_TYPE VARCHAR(20),
ID_DOC_NO VARCHAR(20),
CITIZENSHIP VARCHAR(10),
constraint CUST_PER_INFO_PK primary key(CUSTOMER_ID)
);
-- CUSTOMER_REFERNCE_INFO
CREATE TABLE CUSTOMER_REFERENCE_INFO
(
CUSTOMER_ID VARCHAR(5),
REFERENCE_ACC_NAME VARCHAR(20),
REFERENCE_ACC_NO BIGINT(16),
REFERENCE_ACC_ADDRESS VARCHAR(100),
REALTION VARCHAR(25),
CONSTRAINT CUST_REF_INFO_PK primary key(CUSTOMER_ID),
CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES  CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);

-- BANK INFO
CREATE TABLE BANK_INFO(
IFSC_CODE VARCHAR(15),
BANK_NAME VARCHAR(25),
BRANCH_NAME VARCHAR(25),
CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);
-- ACCOUNT INFO
CREATE TABLE ACCOUNT_INFO(
ACCOUNT_NO BIGINT(16),
CUSTOMER_ID VARCHAR(5),
ACCOUNT_TYPE VARCHAR(10),
REGISTRATION_DATE DATE,
ACTIVATION_DATE DATE,
IFSC_CODE VARCHAR(10),
INTEREST DECIMAL(7,2),
INITIAL_DEPOSIT BIGINT(10),
CONSTRAINT ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
CONSTRAINT ACC_INFO_PERS_FK foreign KEY(CUSTOMER_ID) REFERENCES customer_reference_info(CUSTOMER_ID) ,
CONSTRAINT ACC_INFO_BANK_FK foreign KEY(CUSTOMER_ID) REFERENCES BANK_INFO(IFSC_CODE)
);
-- BANK_INFO
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES('SBICOO8','SBI','JUBLIEHILLS');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES('SBICOO9','SBI','BANJARAHILLS');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES('SBICO10','SBI','VANASTALIPURAM');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES('SBICOO11','SBI','KONDAPUR');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES('SBICOO12','SBI','MANIKONDA');
select * from BANK_INFO;
-- CUSTOMER_PERSONAL_INFO
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DOB,GAURDIAN_NAME,CONTACT_NO,MAIL_ID,GENDER,MARTIAL_STATUS,IDENTICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)
VALUES('1','JAYANTH','2002-03-09','SNMRAO','9988556611','HDU@GMAIL.COM','M','SINGLE','AADHAR','158962','INDIAN');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DOB,GAURDIAN_NAME,CONTACT_NO,MAIL_ID,GENDER,MARTIAL_STATUS,IDENTICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)
VALUES('2','NIKI','2001-03-27','MSRAO','9988556611','HDU@GMAIL.COM','M','SINGLE','AADHAR','158962','INDIAN');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DOB,GAURDIAN_NAME,CONTACT_NO,MAIL_ID,GENDER,MARTIAL_STATUS,IDENTICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)
VALUES('3','MARI','1995-03-09','SKREDDY','9988556611','HDU@GMAIL.COM','M','SINGLE','AADHAR','158962','INDIAN');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DOB,GAURDIAN_NAME,CONTACT_NO,MAIL_ID,GENDER,MARTIAL_STATUS,IDENTICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)
VALUES('4','NITISH','1999-08-09','SFNAIDU','9988556611','HDU@GMAIL.COM','M','SINGLE','AADHAR','158962','INDIAN');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DOB,GAURDIAN_NAME,CONTACT_NO,MAIL_ID,GENDER,MARTIAL_STATUS,IDENTICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)
VALUES('5','MAHA','200-03-27','SNM5','9988556611','HDU@GMAIL.COM','F','SINGLE','AADHAR','158962','INDIAN');
select * from CUSTOMER_PERSONAL_INFO;
-- CUSTOMER REF NO
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,REALTION)
VALUES('1','AVINASH SINHA','156255','5-4-1525/1','COUSIN');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,REALTION)
VALUES('2','KRISHNA CHOWDARY','45862','5-4-1526/1','WIFE');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,REALTION)
VALUES('3','AKASH REDDY','789651','5-4-1527/1','MOTHER');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,REALTION)
VALUES('4','SHIVA GOUD','558513','5-4-1528/1','FATHER');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,REALTION)
VALUES('5','SRINIVAS NAIDU','98634','5-4-1529/1','UNCLE');
select * from CUSTOMER_REFERENCE_INFO;
-- ACCOUNT_INFO

